version: '3.6'

services:

  genelect:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "127.0.0.1:5555:80"
    env_file:
      - env.dev

  db:
    image: mariadb
    restart: always
    env_file:
      - env.dev
    volumes:
      - ../.genelectdb:/var/lib/mysql
