"""empty message

Revision ID: 07acc321a641
Revises: 00befa842b3a
Create Date: 2021-06-09 22:09:33.776723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07acc321a641'
down_revision = '00befa842b3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('completions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('offerings', schema=None) as batch_op:
        batch_op.drop_column('day')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offerings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day', sa.DATE(), nullable=True))

    with op.batch_alter_table('completions', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
